name: sayam-gupta # {your name}-test or some other name that describes the workflow
      # generally the name corresponds to the name of the file, but it can
      # always be different.

on: push

  # when should this run 🤔?
  # use the docs to figure out how to trigger a workflow

jobs:
  build:

    runs-on: ubuntu-latest # Linux FTW!

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build C++ code
        run: g++ main.cpp -o output_binary

      # how many steps do you need and what should they be?
      # what's the best way to split them up to be efficient?
      
